In [1]:
import numpy as np


In [2]:
# 1. Creating  an 1D Array
array_1d = np.array((1,2,3,4,5,6))
print(array_1d)

[1 2 3 4 5 6]


In [3]:
# Creating  an 2D Array
array_2d = np.array([[1,3,2],[4,5,6],[4,5,8]])
print(array_2d)

[[1 3 2]
 [4 5 6]
 [4 5 8]]


In [4]:
# create 3D array
array_3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
# attrbutes in array
print(array_1d.ndim) # dimension of an array
print(array_2d.ndim)
print(array_3d.ndim)

1
2
3


In [7]:
print(array_2d.shape) #  number of rows and columns in an array
print(array_2d.size)  # number of elemments in the an array
print(array_2d.dtype) # datatype of elements
print(array_3d.shape)

(3, 3)
9
int64
(2, 2, 3)


In [ ]:
# indexing and sclicing in an array
print(array_2d)
print(array_2d[2,2])

[[1 3 2]
 [4 5 6]
 [4 5 8]]
8


In [13]:
print(array_2d[0:3:2])

[[1 3 2]
 [4 5 8]]


In [ ]:
print(array_2d[1:2:1])

[[4 5 6]]


In [ ]:
#3x3 array with random ints between 0–9
np.random.randint(10,size=(2,3))


array([[6, 8, 0],
       [5, 9, 3]])

In [14]:
np.random.randint(1,10,4)

array([8, 8, 6, 5])

In [ ]:
# Creating  an zero  Array
zero_array = np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creating  an one Array
one_array = np.ones((2,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#5x5 array of 0 with 1 on diagonal Identitymatrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
from numpy import *
a = arange(12) # an evenly spacing array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
ap= arange(1,8,2)
print(ap)

[1 3 5 7]


In [17]:
a = a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [18]:
a.ndim

3

In [ ]:
trans=np.array([(1,2,3,4),(5,6,7,8)])
trans.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
trans.resize((3,6))
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
a = np.arange(6)
print( a)
a.resize(3, 4)
print(a)

[0 1 2 3 4 5]
[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
#Appends values to end of arr
arr2=np.append(array_2d,[0,1,2,4,5])
arr2

array([1, 3, 2, 4, 5, 6, 4, 5, 8, 0, 1, 2, 4, 5])

In [ ]:
#Inserts values into arr before index 2
np.insert(arr2,5,8)

array([1, 3, 2, 4, 5, 8, 6, 4, 5, 8, 0, 1, 2, 4, 5])

In [ ]:
#Convert arr to a Python list
array_2d.tolist()

[[1, 3, 2], [4, 5, 6], [4, 5, 8]]

In [ ]:
#Array of 5 evenly divided values from 0 to 150
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])