In [28]:
print("Aravind")
print("aravind")

Aravind
aravind


In [26]:
print(Aravind)
print(1+2)

NameError: name 'Aravind' is not defined

In [30]:
a="Aravind"
print(a)

Aravind


In [36]:
a="Rahul"
print(a)

Rahul


In [38]:
A="Christy"
print(a)
print(A)

Rahul
Christy


In [40]:

name="Aravind"
age=22
place="Kottarakara"
print(name)
print(age)
print(place)

Aravind
22
Kottarakara


In [55]:
a="Hello world"
user=1+2
print(a)
print(user)

Hello world
3


In [57]:
input("enter a name ")

enter a name  Aravind


'Aravind'

In [61]:
print(input())

 Aravind


Aravind


In [65]:
name = input()
print(name)

 Aravind


Aravind


In [73]:
name=input("enter name")
age=input("enter age")
place=input("enter place")
print("my name is ",name)
print("my age",age)
print("my place",place)

enter name AK
enter age 22
enter place ktr


my name is  AK
my age 22
my place ktr


In [79]:
c=int(input("enter the celcius"))
f=int(input("enter the farenheat"))
a=c*(9/5)+32
print(a)


enter the celcius 12
enter the farenheat 22


53.6


In [81]:
length =int(input("enter the length"))
breadth=int(input("enter the breadth"))
print("Area is",length*breadth)

enter the length 10
enter the breadth 10


Area is 100


In [5]:
p=int(input("enter the principal amt"))
r=int(input("enter the rate"))
n=int(input("enter the times interest in compounded per year"))
t=int(input("enter the time in  year"))
A=p*(1+(r/n)**n*t)
print("amount :",A)
compount=A-p
print("Compound intrest is :",compount)

enter the principal amt 1000
enter the rate 12
enter the times interest in compounded per year 3
enter the time in  year 4


amount : 257000.0
Compound intrest is : 256000.0


In [17]:
a=int(input("maths"))
b=int(input("physcis"))
avgTestScore=(a+b)/2

print(avgTestScore)
type(a)

maths 10
physcis 20


15.0


int

In [19]:
a=True
type(a)

bool

In [48]:
b=10
a=10.5
print(type(a))
print(type(b))
type(True)


<class 'float'>
<class 'int'>


bool

In [7]:
username=input("enter the user name")
age=input("enter the age")
print("Hello",username+" "+"your age is",age)

enter the user name ram
enter the age 22


Hello ram your age is 22


In [77]:
a=int(input("enter the value"))
if a>0:
    if a%2==0 :
        print("even")
    elif a%2!=0:
        print("odd")
elif a<=0:
    print(f" {a} is 0 or -ve")
    


enter the value -1


 -1 is 0 or -ve


In [96]:
a=int(input("enter the value"))
if a%2==0 :
    print("even")
else  :
    print("odd")

enter the value 2


even


In [102]:
a=[1,2,3,4]
print(max(a))
print(min(a))

4
1


In [106]:
a=[1,2,3,4]
print(sum(a))

10


In [110]:
a="Hello world"
print(len(a))

11


In [124]:
a=10
b=20
c=a
a=b
b=c
print(a)
print(b)


20
10


In [191]:
a="Hello World"
print(a[6:-1])

Worl


In [205]:
a=["Rahul","rahesh"]
# b=["Ramu","shibu"]
c=a[0]+a[1]
print(c.split("l"))

['Rahu', 'rahesh']


In [222]:
a="hello world"
b="a,e,i,o,u,A,E,I,O,U"
count=0
for x in a:
    if x in b:
        count+=1
print(count)
    

3


In [234]:
l1=input("input letter only")
n1=input("enter number only")
n2=input("input number only")
l2=input("input letter only")
print("postcode :",l1+n1+" "+n2+l2)

input letter only KY
enter number only 8
input number only 9
input letter only HI


postcode : KY8 9HI


In [242]:
l1=input("input letter only")
n1=input("enter number only")
n2=input("input number only")
l2=input("input letter only")
value=l1+n1+" "+n2+l2
print(value.upper())

input letter only ki
enter number only 8
input number only 9
input letter only hi


KI8 9HI


In [272]:
a=input("enter forename")
b=input("enter lastname")
c=a+b
print(len(c))

enter forename ram
enter lastname mohan


8


In [282]:
a="he should always ensure that his answer should always contain as much details as possible"
c=a.replace("he","she")
d=c.replace("his","her")
print(d)

she should always ensure that her answer should always contain as much details as possible


In [284]:
name=input("enter the name of the product ")
year=input("enter the year of the product ")
front=name[0:2]
back=name[-2:]
last=year[-2:]
out=front+back+last
print(out)


enter the name of the product  toothbrush
enter the year of the product  2017


tosh17


In [294]:
name=input("enter the string")
c=name[::-1]
print(c)
if name==c:
    print("pallindrom")
else:
    print("NOT PALLINDROM")

enter the string hello


olleh
NOT PALLINDROM


In [336]:
number=int(input("enter the number"))
if number==2 or number%2!=0 and number%5!=0:
    print("prime")
else :
    if number%2==0 or number%5==0:
        print(" not prime")
   
        


enter the number 21


prime


In [338]:
print(range(1,10))

range(1, 10)


In [342]:
for x in range(1,11):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [358]:
age=int(input("please enter the age"))
if age>=5 and age<=17:
    print("please buy junior ticket")
elif age>17 and age<65:
     print("please buy adult ticket")
elif age==65:
    print("plese buy senior ticket")
else :
    print("thanks for the enquirey")

please enter the age 67


thanks for the enquirey


In [364]:
a=int(input("maths"))
b=int(input("physcis"))
avgTestScore=(a+b)/2
if avgTestScore<80:
     print("does not achieved the limit")
else:
    print("wow achived")

maths 100
physcis 100


wow achived


In [378]:
age=int(input("please enter the age"))
if age<=10 :
    print("children")
elif age>60 :
     print("senior citizen")
elif age>10 and age<65:
    print("normal citizen")


please enter the age 10


children


In [396]:
age=int(input("please enter the age"))
gender=input("Enter the gender")
if gender=="male" and age>60:
    print("70% fair is applicable")
elif  gender=="female" and age>60:
    print("50% fair is applicable") 
elif  gender=='female" and age<60:
    print("50% fair is applicable") 
elif  gender=='male' and age>10 and age<65:
    print("50% fair is applicable") 



please enter the age 61
Enter the gender male


70% fair is applicable


In [398]:
for x in range(0,11):
    print(x)

0
1
2
3
4
5
6
7
8
9
10


In [419]:
for x in range(0,11):
    print(f"2 x {x} = {2 * x}")


2 x 0 = 0
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [425]:
num=int(input())
fact=1
for x in range(1,num+1):
    fact=fact*x
print(fact)

 11


39916800


In [445]:
for i in range(2,51):
    if i>1:
        for x in range(2,int(i**0.5)+1):
            if i % x == 0:
               break
        else:
            print(i)

    
            
    

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [451]:
num=int(input())
sum=0
for x in range(1,num+1):
    sum=sum+x
print(sum)

 10


55


In [485]:
passcode=input("enter the password")
orginal="hello"
while passcode!=orginal:
    passcode=input("enter the password")
    if passcode==orginal:
        print(orginal)
        


enter the password hhjj
enter the password jjjk
enter the password jjkk
enter the password jjj
enter the password hello


hello


In [497]:
n=int(input("enter the number"))
if n%2==0:
    print("even")
else:
    print("odd")

enter the number 98


even


In [511]:
for x in range(1,10):
    print(x*"*")

*
**
***
****
*****
******
*******
********
*********


In [539]:
for x in range(10,1,-1):
    print(x*"*")

**********
*********
********
*******
******
*****
****
***
**


In [543]:
for x in range(1,10):
    print(x*"*")
for x in range(10,1,-1):
    print(x*"*")
    

*
**
***
****
*****
******
*******
********
*********
**********
*********
********
*******
******
*****
****
***
**


In [549]:
a=int(input("enter the first number"))
b=int(input("enter the last number"))
for x in range(a,(b)+1,2):
            print(x)


enter the first number 23
enter the last number 97


23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97


In [555]:
a=input("would you like to get advice or not.plese enter the yes or no")
if a=="yes" or a=="y":
    print("i will give advice")
elif a=="no" or a=="n":
    print("feel free to ask")



would you like to get advice or not.plese enter the yes or no n


feel free to ask


In [639]:
num=int(input("plese enter a number between 1 and 100"))
guess=50


while guess!=num:
    print("wrong guess")
    # num=int(input("plese enter again"))
    if num<1 or num>100:
        pass
    num=int(input("plese enter a number between 1 and 100"))
            
            
if 1<=num<=100:
    if guess==num:
        print("your guess is correct")            
        


plese enter a number between 1 and 100 67


wrong guess


plese enter a number between 1 and 100 33


wrong guess


plese enter a number between 1 and 100 50


your guess is correct


In [649]:
num=int(input("enter the money"))
a=0
while num<200 and a<200:
    num=int(input("limit not exceeded"))
    a+=num
if num==200 or a==200:
    print("limit")
    

enter the money 200


limit


In [671]:
count=int(input("enter the number of collection"))
i=1
amt=0
while i<=count:
    x=int(input("enter the collection amount"))
    amt=amt+x
    i+=1
print(amt)
    

enter the number of collection 5
enter the collection amount 100
enter the collection amount 100
enter the collection amount 100
enter the collection amount 100
enter the collection amount 100


500


In [722]:
a=int(input("enter the first number"))
b=int(input("enter the last number"))

while b<20+a:
    print(f"please enter a number grater than {20+a}")
    b=int(input("please enter the number again"))
    pass
    for x in range(a,(b)+1,2):
            print(x)




enter the first number 5
enter the last number 2


please enter a number grater than 25


please enter the number again 26


5
7
9
11
13
15
17
19
21
23
25


In [7]:
a=int(input("please enter the first odd number"))
b=int(input("please enter the second  oddnumber"))
while a%2==0 and b%2==0:
    print("enter the odd number")
    a=int(input("please enter the first odd  number again"))
    b=int(input("please enter the second odd number again"))
    pass
if a%2!=0 and b%2!=0:
    c=b**2
    for x in range(a,c,2):
        print(x)






please enter the first odd number 1
please enter the second  oddnumber 9


1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79


In [61]:
i=1
sum=0
while i<=7:
    temp=float(input("enter the temp"))
    sum+=temp
    i+=1

print(f"sum is{sum}")
avg=sum/7
print(f"average is {avg}")
rounds=round(avg,2)
print(f"rounded average is{rounds}")





enter the temp /


ValueError: could not convert string to float: '/'

In [63]:
fruits=["apple","orange","pinapple","mango"]
fruits.append("cherry")
print(fruits)
# fruits

['apple', 'orange', 'pinapple', 'mango', 'cherry']


In [67]:
fruits=["apple","orange","pinapple","mango"]
fruits.insert(1,"muzambi")
print(fruits)

['apple', 'muzambi', 'orange', 'pinapple', 'mango']


In [69]:
fruits=["apple","orange","pinapple","mango"]
fruits.extend(["rambootan","Aaron"])
print(fruits)

['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron']


In [73]:
fruits=['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron']
fruits.remove("Aaron")
print(fruits)

['apple', 'orange', 'pinapple', 'mango', 'rambootan']


In [77]:
fruits=['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron']
fruits.pop(1)
print(fruits)

['apple', 'pinapple', 'mango', 'rambootan', 'Aaron']


In [85]:
fruits=['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron',"orange"]
c=fruits.count("orange")
print(c)

2


In [99]:
fruits=['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron',"orange"]
fruits.sort(reverse=False,key=len)
print(fruits)

['apple', 'mango', 'Aaron', 'orange', 'orange', 'pinapple', 'rambootan']


In [115]:
teamScore=[0]*3
print(teamScore)

[0, 0, 0]


In [ ]:
teamNames=[""]*10
print(teamNames)

In [147]:
fruits=[]
fruits.append("apple")
fruits.append("orange")
fruits.append("pinapple")
print(fruits)

['apple', 'orange', 'pinapple']


In [149]:
fruits=['apple', 'orange', 'pinapple', 'mango', 'rambootan', 'Aaron',"orange"]
for x in fruits:
    print(x)

apple
orange
pinapple
mango
rambootan
Aaron
orange


In [27]:
fruits=[]
for x in range(1,5):
    c=input("enter into list")
    fruits.append(c)
print(fruits)
    


enter into list apple
enter into list orange
enter into list pina
enter into list mango


['apple', 'orange', 'pina', 'mango']


In [35]:
fruits=[]
i=0
while i<4:
    c=input("enter into list")
    fruits.append(c)
    i+=1
print(fruits)
    


enter into list apple
enter into list orange
enter into list mango
enter into list kiwi


['apple', 'orange', 'mango', 'kiwi']


In [53]:
fruits=[[]*2 for i in range(3)]
print(fruits)

[[], [], []]


In [11]:
fruits=[["apple"]*2 for x in range(1,5)]
print(fruits)

[['apple', 'apple'], ['apple', 'apple'], ['apple', 'apple'], ['apple', 'apple']]


In [87]:
fruits=[[]*2 for x in range(2)]
c=input("enter the fruits")
fruits.insert(0,c)
print(fruits)

enter the fruits apple


['apple', [], []]


In [95]:
list1=int(input("enter the number of dimensional list"))
fruits=[[]*2 for x in range(list1)]
x=input("enter the element to be inserted")
position=int(input("enter the index to enter the list element"))

fruits.insert(position,x)
print(fruits)


enter the number of dimensional list 4
enter the element to be inserted apple
enter the index to enter the list element 1


[[], 'apple', [], [], []]


In [31]:

fruits=[[""]*2 for x in range(5)]
for x in range(5):
    for y in range(2):
        print(x,y)
        fruits[x][y]=input("enter the values")
print(fruits)

for x,y in fruits:
    print(x,y)


0 0


enter the values apple


0 1


enter the values orange


1 0


enter the values muzambi'mango


1 1


enter the values kiwi


2 0


enter the values cherry


2 1


enter the values mashmello


3 0


enter the values rambootan


3 1


enter the values carrot


4 0


enter the values oreo


4 1


enter the values leaves]=


[['apple', 'orange'], ["muzambi'mango", 'kiwi'], ['cherry', 'mashmello'], ['rambootan', 'carrot'], ['oreo', 'leaves]=']]
apple orange
muzambi'mango kiwi
cherry mashmello
rambootan carrot
oreo leaves]=


In [59]:
dicto={"name":"Aravind","Age":22}
print(dicto)
dicto["grade"]="A"
print(dicto)
dicto.items()
dicto.get("name")
dicto.keys()
dicto.pop("Age")
print(dicto)
dicto.values()
dicto1={"name":"Aaron","Age":22}
dicto.update(dicto1)
print(dicto)
type(dicto)
type(fruits)

{'name': 'Aravind', 'Age': 22}
{'name': 'Aravind', 'Age': 22, 'grade': 'A'}
{'name': 'Aravind', 'grade': 'A'}
{'name': 'Aaron', 'grade': 'A', 'Age': 22}


list

In [5]:
l1=["aravind", "aaron","Ashkar"]
print(l1)
print(max(l1))

['aravind', 'aaron', 'Ashkar']
aravind


In [15]:
l1=["aravind", "aaron","Ashkar","Ashkar"]
for x in l1:
    print(l1.count(x))
    


1
1
2
2


In [19]:
l1=["aravind", "aaron","Ashkar","Ashkar"]
print(set(l1))

{'aravind', 'Ashkar', 'aaron'}


In [35]:
l1=["aravind", "aaron","Ashkar","Ashkar"]
l1.sort(key=len,reverse=True)
print(l1)

['aravind', 'Ashkar', 'Ashkar', 'aaron']


In [43]:
l2=["aravind", "aaron","Ashkar","Ashkar"]
l2.sort()
print(l2)

['Ashkar', 'Ashkar', 'aaron', 'aravind']


In [65]:
l2=[]
x=1
while x<=5:
    c=input("enter the element to append")
    l2.append(c)
    x+=1
print(l2)
if l2!=l2.sort():
    l2.sort()
    print(l2)


enter the element to append ram
enter the element to append mohan
enter the element to append arun
enter the element to append arjun
enter the element to append syam


['ram', 'mohan', 'arun', 'arjun', 'syam']
['arjun', 'arun', 'mohan', 'ram', 'syam']


In [17]:
l1=["Aravind","Ananth"]
l2=["Ram","Ashkar"]
set1=set(l1)
set2=set(l2)
print(set1|set2)

Key with highest value: c
Highest value: 35


In [19]:
my_dict = {'a': 10, 'b': 25, 'c': 5}

max_key = max(my_dict, key=my_dict.get)

print("Key with highest value:", max_key)
print("Highest value:", my_dict[max_key])d


Key with highest value: b
Highest value: 25


In [3]:
l1=["Aravind","Ananth"]
l2=["Ram","Ashkar","Aravind"]
set1=set(l1)
set2=set(l2)
print(set1|set2)
print(set1-set2)
print(set1^set2)

{'Aravind', 'Ram', 'Ananth', 'Ashkar'}
{'Ananth'}
{'Ashkar', 'Ram', 'Ananth'}


In [383]:
from operator import itemgetter

# Input: list of dictionaries
people = [
    {"name": "Aravind"},
    {"name": "Ram"},
    {"name": "Arcite"}
]

# Sort by the 'name' key using itemgetter
people.sort(key=itemgetter("name"))

print(people)


[{'name': 'Aravind'}, {'name': 'Arcite'}, {'name': 'Ram'}]


In [72]:

text = input("Enter a string: ")
char_count = {}
for char in text:
    if char in char_count:
        char_count[char] += 1 
    else:
        char_count[char] = 1   
print("Character frequencies:")
for char, count in char_count.items():
    print(f"'{char}': {count}")


Enter a string:  hello


Character frequencies:
'h': 1
'e': 1
'l': 2
'o': 1


In [385]:
words=["Aravind","Ashkar","Ram",]
# print(words[0])
common=set(words[0])
for x in words:
     common = common & set(x)
print("Common characters:", common)


Common characters: {'a'}


In [147]:
l1=[{'val':1},{'val':3}]
l2=[]
val=0

print(l1)
for x in l1:
    value=list(x.values())
    l2.append(value)
    # for x in l2:
    #     val+=x
print(l2)
 
    

[{'val': 1}, {'val': 3}]
[[1], [3]]


In [153]:
def name(*args):
    print(args)
name("Aravind","Aaron")

('Aravind', 'Aaron')


In [157]:
def name(**kwargs):
    print(kwargs)
name(name="Ak",Age="22")

{'name': 'Ak', 'Age': '22'}


In [165]:
def add_numbers(*args):
    total=0
    for x in args:
        total+=x
    print("total",total)
add_numbers(10,20)
add_numbers(10,20,30)
        
        

total 30
total 60


In [171]:
def print_info(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}:{value}")
print_info(name="AK",age=22,place="ktr")

name:AK
age:22
place:ktr


In [173]:
def name(name):
    print(name)
name("Aravind")

Aravind


In [189]:
h=lambda name:name
h("Aravind")

'Aravind'

In [193]:
a=lambda a,b:a+b
a(1,2)

3

In [3]:

a=lambda a:print("even") if a%2==0 else print("odd")
a(int(input()))

 2


even


even


In [221]:
def even(a):
    if a%2==0:
        print("even")
    else:
        print("odd")
even(5)
    

odd


In [236]:
list1=[1,2,3,4,5,6]
a=list(map(lambda x:x**2,list1))
print(a)


[1, 4, 9, 16, 25, 36]


In [240]:
list2=list1.copy()
print(list2)

[1, 2, 3, 4, 5, 6]


In [244]:
list1=[1,2,3,4,5,6]
a=list(filter(lambda x:x%2==0,list1 ))
print(a)

[2, 4, 6]


In [250]:
from functools import reduce
list1=[1,2,3,4,5,6]
a=reduce(lambda x,y:x+y,list1)
print(a)

21


In [261]:

def sum(*args):
    sum=0
    for x in args:
        sum+=x
    print(sum)
sum(20,30)

50


In [271]:
def pallindrom(text):

    if text == text[::-1]:
        print("It's a palindrome!")
    else:
        print("Not a palindrome.")
pallindrom("aravind")

Not a palindrome.


In [275]:
list1=[1,2,3,4,5,6]
a=list(map(lambda x:x**2,list1))
print(a)

[1, 4, 9, 16, 25, 36]


In [289]:
c=lambda a:print("even") if a%2==0 else print("odd")
c(int(input()))

 5


odd


In [299]:
x=lambda x,y:print((1/2)*x*y)
x(10,20)

100.0


In [347]:
def sort1():
    return list(args).sort()

n=sort1(["z","c","a"])
print(n)

None


In [17]:
c= lambda x:sorted(x)
c("bcda")

['a', 'b', 'c', 'd']

In [361]:
def s1():
    c=["Aravind","Aaron"]
    c.sort()
    print(c)
s1()
    

['Aaron', 'Aravind']


In [367]:
def intersection():
    l1=[1,2,3,4,5]
    l2=[2,1,5]
    c=set(l1)
    d=set(l2)
    print(c&d)
intersection()

{1, 2, 5}


In [371]:
def leapyear(year):
    if (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0):
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")
leapyear(2000)

2000 is a leap year.


In [377]:
def multiplicationTable(num):

    print(f"\nMultiplication Table of {num}:")

    for i in range(1, 11):
        print(f"{num} x {i} = {num * i}")
multiplicationTable(2)



Multiplication Table of 2:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [3]:
# numpy
import numpy as np

arr=np.array((1,2,3,4,5))
print(arr)


[1 2 3 4 5]


In [7]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [15]:
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
threeD=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
print(arr.ndim)
print(twoD.ndim)
print(threeD.ndim)


1
2
3


In [39]:
print(arr.shape)
print(arr.size)
print(arr.dtype)


(5,)
5
int32
(5,)


In [43]:
print(twoD.shape)
print(twoD.size)
print(twoD.dtype)


(3, 3)
9
int32


In [47]:
print(twoD)
print(twoD[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [51]:
print(twoD[0:3:2])

[[1 2 3]
 [7 8 9]]


In [57]:
print(twoD[1:3:2])

[[4 5 6]]


In [67]:
np.random.randint(1,10,10)

array([4, 8, 8, 2, 6, 9, 4, 1, 1, 7])

In [69]:
np.random.randint(10,size=(2,3))

array([[6, 3, 9],
       [1, 8, 8]])

In [73]:
zero_array=np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [75]:
ones_array=np.ones((2,3))
print(ones_array) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
from numpy import*
a=arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
ap=arange(1,10,2)
print(ap)

[1 3 5 7 9]


In [91]:
a=a.reshape(3,3,2)
print(a)

ValueError: cannot reshape array of size 12 into shape (3,3,2)

In [116]:
from numpy import*


SyntaxError: invalid syntax (3232349971.py, line 1)

In [104]:
arr=np.array([1,3,3])
print(sum(arr))
print(prod(arr))

7
9


In [122]:
a=random.randint(1,100,10)
print(mean(a))
print(median(a))
print(std(a))
print(a)

45.6
41.0
33.341265722824616
[ 6 95 87  8 57 87 32 43 39  2]


In [124]:
a=arange(24)
print(a.reshape(2,12))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [130]:
a=np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
a=np.array((1,5,2,3,9,6))
a.sort()
desc=sorted(a,reverse=True)
print(desc)
print(a)

[9, 6, 5, 3, 2, 1]
[1 2 3 5 6 9]


In [156]:

a=np.array(([1,2,3],
            [4,5,6]))
print("sum of rows",a.sum(axis=1))
print("sum of column",a.sum(axis=0))

sum of rows [ 6 15]
sum of column [5 7 9]


In [174]:
a=random.randint(1,10,5)
print(a)
print(max(a))
print(min(a))

[3 1 5 4 2]
5
1


In [198]:
a=np.array([1,2,3,4,5])
print(a)
print("squre :-",a**2)

[1 2 3 4 5]
squre :- [ 1  4  9 16 25]


In [230]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.dot(a,b)
print(c)

32


In [264]:
x=np.array([[1,2],
            [4,5]])
c=np.linalg.inv(x)
print("Iverse matrix is :-",c)

Iverse matrix is :- [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [273]:
def fact(n):
    if n==1:
        return 1
    return fact(n-1)*n
fact(10)

3628800

In [279]:
def sum(n):
    if n==1 or n==0:
        return 1
    else:
       return sum(n-1)+n
sum(5)

15

In [9]:
import numpy as np
from scipy import stats
arr=np.array([190,153,168,179,194,153,165,187,190,170,165,189,185,153,147,161,127,180])

print(np.mean(arr))
print(np.median(arr))
print(stats.mode(arr))


169.77777777777777
169.0
ModeResult(mode=153, count=3)


In [29]:
import numpy as np
arr = np.array([
    [[10, 20, 30, 40, 50],
     [15, 25, 35, 45, 55],
     [5, 10, 15, 20, 25]],

    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15]]
])
print(arr)
percentile_80=np.percentile(arr,80 ,axis=2)
print("80th Percentile along axis 1:")
print(percentile_80)

[[[10 20 30 40 50]
  [15 25 35 45 55]
  [ 5 10 15 20 25]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
80th Percentile along axis 1:
[[42.  47.  21. ]
 [ 4.2  9.2 14.2]]


In [17]:
import numpy as np
arr=np.array([1,2,3,5,5])
sd=np.std(arr)
variance=np.var(arr)
print("standard deviation",sd)
print("variance",variance)

standard deviation 1.6
variance 2.56


In [31]:
import numpy as np


x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

cov_matrix = np.cov(x, y)

print("Covariance matrix:\n", cov_matrix)

Covariance matrix:
 [[ 2.5  5. ]
 [ 5.  10. ]]


In [33]:
import numpy as np

ages = np.array([
    18, 21, 22, 25, 26, 27, 29, 30, 31, 33,
    36, 37, 41, 42, 47, 52, 55, 57, 58, 62,
    64, 67, 69, 71, 72, 73, 74, 76, 77
])

p70 = np.percentile(ages, 70)
p83 = np.percentile(ages, 83)

print("70th Percentile:", p70)
print("83rd Percentile:", p83)


70th Percentile: 63.199999999999996
83rd Percentile: 71.24


In [39]:
import numpy as np
weights = np.array([46, 48, 50, 52, 53, 54, 55])
frequencies = np.array([7, 5, 8, 12, 10, 2, 1])
expanded_data = np.repeat(weights, frequencies)
median_weight = np.median(expanded_data)

print("Median Weight:", median_weight)


Median Weight: 52.0


In [9]:
import numpy as np

arr = np.array([
    [0, 1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10, 11]
])

diff = np.max(arr, axis=1) - np.min(arr, axis=1)

# Print results
print("Original array:")
print(arr)

print("Difference between the maximum and minimum values:")
print(diff)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Difference between the maximum and minimum values:
[5 5]


In [43]:
import pandas as pd


In [49]:
pd.read_csv(r"C:\Users\anant\Downloads\titanic.csv",nrows=50)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [220]:
df = pd.DataFrame([[1, 2], [4, 5], [None, 8]],
                    index=['cobra', 'viper', 'sidewinder'],
                    columns=['max_speed', 'shield'])
df
    

,max_speed,shield
cobra,1.0,2
viper,4.0,5
sidewinder,NaN,8


In [221]:
df.shape


(3, 2)

In [224]:
df.head(2)

,max_speed,shield
cobra,1.0,2
viper,4.0,5


In [226]:
df.tail(2)

,max_speed,shield
viper,4.0,5
sidewinder,NaN,8


In [21]:
df.columns


NameError: name 'df' is not defined

In [19]:
for i in df.columns:
    print(max(df[i]))

NameError: name 'df' is not defined

In [231]:
df["max_speed"]

cobra         1.0
viper         4.0
sidewinder    NaN
Name: max_speed, dtype: float64

In [234]:
df.dtypes

max_speed    float64
shield         int64
dtype: object

In [236]:
df.index

Index(['cobra', 'viper', 'sidewinder'], dtype='object')

In [238]:
df.describe()

,max_speed,shield
count,2.00000,3.0
mean,2.50000,5.0
std,2.12132,3.0
min,1.00000,2.0
25%,1.75000,3.5
50%,2.50000,5.0
75%,3.25000,6.5
max,4.00000,8.0


In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, cobra to sidewinder
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   max_speed  2 non-null      float64
 1   shield     3 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 180.0+ bytes


In [242]:
df.count()

max_speed    2
shield       3
dtype: int64

In [244]:
df["max_speed"].count()

2

In [245]:
df["max_speed"].value_counts()

max_speed
1.0    1
4.0    1
Name: count, dtype: int64

In [248]:
df["max_speed"].sum()

5.0

In [250]:
df[df["max_speed"]<4].mean()

max_speed    1.0
shield       2.0
dtype: float64

In [255]:
df1=df.drop(["max_speed"],axis=1)
df1

,shield
cobra,2
viper,5
sidewinder,8


In [263]:
df["shield"].loc["cobra"]

2